//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHYL.Lottery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetChildRecord
    {
        public int Id { get; set; }
        public Nullable<int> BetRecordId { get; set; }
        public Nullable<int> BetBallNo { get; set; }
        public string BetType { get; set; }
        public string BetInfo { get; set; }
        public Nullable<double> Odds { get; set; }
        public Nullable<decimal> BetMoney { get; set; }
        public string LotteryType { get; set; }
        public string Expect { get; set; }
        public string WinState { get; set; }
    }
}
