//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHYL.Lottery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetRecord
    {
        public int Id { get; set; }
        public string Expect { get; set; }
        public Nullable<System.DateTime> BetTime { get; set; }
        public Nullable<decimal> BetMoney { get; set; }
        public Nullable<int> BetCount { get; set; }
        public string LotteryState { get; set; }
        public string BetUser { get; set; }
        public string LotteryType { get; set; }
        public Nullable<decimal> TotalWinOrLose { get; set; }
    }
}
