//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHYL.Lottery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryResult
    {
        public int Id { get; set; }
        public string Expect { get; set; }
        public string Opencode { get; set; }
        public Nullable<System.DateTime> Opentime { get; set; }
        public string LotteryType { get; set; }
        public string NextExpect { get; set; }
        public Nullable<System.DateTime> NextOpenTime { get; set; }
    }
}
