//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHYL.Lottery.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotteryEntities : DbContext
    {
        public LotteryEntities()
            : base("name=LotteryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Account> Account { get; set; }
        public DbSet<RechargeRecord> RechargeRecord { get; set; }
        public DbSet<CashRecord> CashRecord { get; set; }
        public DbSet<LotteryResult> LotteryResult { get; set; }
        public DbSet<BetChildRecord> BetChildRecord { get; set; }
        public DbSet<BetRecord> BetRecord { get; set; }
    }
}
