//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHYL.Lottery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Account = new HashSet<Account>();
            this.RechargeRecord = new HashSet<RechargeRecord>();
            this.CashRecord = new HashSet<CashRecord>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public string CreateBy { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<RechargeRecord> RechargeRecord { get; set; }
        public virtual ICollection<CashRecord> CashRecord { get; set; }
    }
}
